// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {encryption} from '../models';
import {api} from '../models';

export function CreateEncryptionGroup(arg1:string,arg2:Array<string>):Promise<{[key: string]: Array<number>}>;

export function GroupDecrypt(arg1:string,arg2:string,arg3:Array<number>):Promise<encryption.DecryptedMessage>;

export function GroupEncrypt(arg1:string,arg2:Array<number>):Promise<encryption.EncryptedMessage>;

export function InitializeKeyStore():Promise<api.KeyBundle>;

export function ProcessSenderKeyDistributionMessage(arg1:string,arg2:string,arg3:Array<number>):Promise<void>;
