// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt(arg1, arg2) {
  return window['go']['encryption']['Manager']['Decrypt'](arg1, arg2);
}

export function Encrypt(arg1, arg2) {
  return window['go']['encryption']['Manager']['Encrypt'](arg1, arg2);
}

export function GetCurrentMaterial(arg1) {
  return window['go']['encryption']['Manager']['GetCurrentMaterial'](arg1);
}

export function InitializeKeyStore() {
  return window['go']['encryption']['Manager']['InitializeKeyStore']();
}
