// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEncryptionGroup(arg1, arg2) {
  return window['go']['encryption']['Manager']['CreateEncryptionGroup'](arg1, arg2);
}

export function GroupDecrypt(arg1, arg2, arg3) {
  return window['go']['encryption']['Manager']['GroupDecrypt'](arg1, arg2, arg3);
}

export function GroupEncrypt(arg1, arg2) {
  return window['go']['encryption']['Manager']['GroupEncrypt'](arg1, arg2);
}

export function InitializeKeyStore() {
  return window['go']['encryption']['Manager']['InitializeKeyStore']();
}

export function ProcessSenderKeyDistributionMessage(arg1, arg2, arg3) {
  return window['go']['encryption']['Manager']['ProcessSenderKeyDistributionMessage'](arg1, arg2, arg3);
}
