// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {encryption} from '../models';
import {api} from '../models';

export function Decrypt(arg1:Array<number>,arg2:string):Promise<encryption.DecryptedMessage>;

export function Encrypt(arg1:Array<number>,arg2:string):Promise<encryption.EncryptedMessage>;

export function EncryptionMaterial(arg1:string):Promise<encryption.Material>;

export function InitializeKeyStore():Promise<api.KeyBundle>;
