// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SignIn(arg1:string,arg2:string):Promise<main.User>;

export function SignOut():Promise<void>;

export function SignUp(arg1:string,arg2:string):Promise<main.User>;
