// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SignIn(arg1, arg2) {
  return window['go']['main']['Auth']['SignIn'](arg1, arg2);
}

export function SignOut() {
  return window['go']['main']['Auth']['SignOut']();
}

export function SignUp(arg1, arg2) {
  return window['go']['main']['Auth']['SignUp'](arg1, arg2);
}
