// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConversation(arg1, arg2) {
  return window['go']['main']['ConversationService']['CreateConversation'](arg1, arg2);
}

export function ListConversations() {
  return window['go']['main']['ConversationService']['ListConversations']();
}

export function ListMessages(arg1) {
  return window['go']['main']['ConversationService']['ListMessages'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['ConversationService']['SendMessage'](arg1, arg2);
}
