// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateConversation(arg1:string,arg2:Array<string>):Promise<models.Conversation>;

export function ListConversations():Promise<Array<models.Conversation>>;

export function ListMessages(arg1:string):Promise<Array<models.Message>>;

export function SendMessage(arg1:string,arg2:string):Promise<models.Message>;

export function SetContext(arg1:context.Context):Promise<void>;
