// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateConversation(arg1:string,arg2:string,arg3:string):Promise<main.Conversation>;

export function ListConversations():Promise<Array<main.Conversation>>;

export function ListMessages(arg1:string):Promise<Array<main.Message>>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<main.Message>;
